# Generated by Django 2.2.11 on 2020-03-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
